version: '2'
services:
    etatcivil-app:
        image: etatcivil
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://etatcivil-mysql:3306/etatcivil?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=etatcivil-elasticsearch:9300
        ports:
            - 8080:8080
    etatcivil-mysql:
        extends:
            file: mysql.yml
            service: etatcivil-mysql
    etatcivil-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: etatcivil-elasticsearch
